# -*- coding: utf-8 -*-
"""Character_detection_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LAteeGz8pefjSEE3ouu2kdTJzyY6Jog5
"""

# segementation model

#downloading dependencies
!pip install ultralytics
!pip install roboflow

# annotated image using roboflow

# searching location for fiel
import os
for root, dirs, files in os.walk('/content'):
    for file in files:
        if file == 'data.yaml':
            print(os.path.join(root, file))


#output:/content/charcter-recognition-1/data.yaml

#using the model YOLO version 8 small model


model = YOLO("yolov8s.pt")
model.train (data ="/content/charcter-recognition-1/data.yaml", epochs = 10, imgsz = 640)

#using the bestmodel
model= YOLO('best(individual_character_recognition_yolo).pt')
print(model.names)

from google.colab import files

model = files.upload()

# checking accuracy
metrics = model.val(split='test')

# Print all key metrics
print(f"mAP50:     {metrics.box.map50:.3f}")
print(f"Precision: {metrics.box.mp:.3f}")
print(f"Recall:    {metrics.box.mr:.3f}")


#output
# mAP50:     0.990
# Precision: 0.984
# Recall:    0.975

# checking model
import cv2
from google.colab import files
from google.colab.patches import cv2_imshow

# img choose garna ko lagi
uploaded = files.upload()

#image ko naam
uploaded_image_name = list(uploaded.keys())[0]


# hamro model ko prediction
results = model.predict(
    source=uploaded_image_name,
    show_labels = False,
    conf=0.5,
    save=True
)

output_path = f'/content/runs/detect/predict/{uploaded_image_name}'
cv2_imshow(cv2.imread(output_path))