# -*- coding: utf-8 -*-
"""LPR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rz2467YUrwsfDL_UyCBEZ3XrCy9js4Wz
"""

# data collection!!

#installation ultralytics, roboflow
!pip install ultralytics
!pip install roboflow

# importing yolo
from ultralytics import YOLO

# Using a pretrained model the LP detection from the image

#using the model YOLO version 8 small model
model = YOLO("yolov8s.pt")

# already imported the images with annotation from roboflow through a api call!

#location of dataset
import os
for root, dirs, files in os.walk('/content'):
    for file in files:
        if file == 'data.yaml':
            print(os.path.join(root, file))

# # trained the model and saved in the computer
# model= YOLO("yolov8s.pt")
# model.train(data='/content/LPR-1/data.yaml', epochs=20, imgsz = 640)
# # downloading the best(LP detection).pt for now

from google.colab import files

# This opens a file picker — select your best.pt from your computer
uploaded = files.upload()

model= YOLO('best(LP dectection).pt')
print(model.names)
model.model.names[0] = 'License_plate'
print(model.names)

import cv2
from google.colab import files
from google.colab.patches import cv2_imshow

# img choose garna ko lagi
uploaded = files.upload()

#image ko naam
uploaded_image_name = list(uploaded.keys())[0]


# hamro model ko prediction
results = model.predict(
    source=uploaded_image_name,
    show_labels = True,
    conf=0.5,
    save=True
)

output_path = f'/content/runs/detect/predict-2/{uploaded_image_name}'
cv2_imshow(cv2.imread(output_path))

