# -*- coding: utf-8 -*-
"""LPR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rz2467YUrwsfDL_UyCBEZ3XrCy9js4Wz
"""

# data collection!!

#installation ultralytics, roboflow
!pip install ultralytics
!pip install roboflow

# importing yolo
from ultralytics import YOLO

# Using a pretrained model the LP detection from the image

#using the model YOLO version 8 small model
model = YOLO("yolov8s.pt")

# already imported the images with annotation from roboflow through a api call!

#location of dataset
import os
for root, dirs, files in os.walk('/content'):
    for file in files:
        if file == 'data.yaml':
            print(os.path.join(root, file))

# # trained the model and saved in the computer
# model= YOLO("yolov8s.pt")
# model.train(data='/content/LPR-1/data.yaml', epochs=20, imgsz = 640)
# # downloading the best(LP detection).pt for now

from google.colab import files

# This opens a file picker — select your best.pt from your computer
uploaded = files.upload()

model= YOLO('best(LP dectection).pt')
print(model.names)
model.model.names[0] = 'License_plate'
print(model.names)

import cv2
from google.colab import files
from google.colab.patches import cv2_imshow

# img choose garna ko lagi
uploaded = files.upload()

#image ko naam
uploaded_image_name = list(uploaded.keys())[0]


# hamro model ko prediction
results = model.predict(
    source=uploaded_image_name,
    show_labels = True,
    conf=0.5,
    save=True
)

output_path = f'/content/runs/detect/predict-2/{uploaded_image_name}'
cv2_imshow(cv2.imread(output_path))

#!pip install easyocr

import easyocr
import cv2
import numpy as np

# Loop through each detected plate
for result in results:
    boxes = result.boxes
    img = cv2.imread(uploaded_image_name)

    for box in boxes:
        # Get bounding box coordinates
        x1, y1, x2, y2 = map(int, box.xyxy[0])

        # Crop just the license plate region
        cropped_plate = img[y1:y2, x1:x2]

        # Run OCR on the cropped plate
        ocr_results = reader.readtext(cropped_plate)

        # Print detected text
        for (bbox, text, confidence) in ocr_results:
            print(f"Plate Text: {text}  |  Confidence: {confidence:.2f}")

        # Optionally display the cropped plate
        cv2_imshow(cropped_plate)


#-----------Preprocessing part-------------------------------

#UPSCALE Image

cropped_plate = cv2.resize(
    cropped_plate,
    None,
    fx=3,
    fy=3,
    interpolation=cv2.INTER_CUBIC
)

cv2_imshow(cropped_plate)

#Convert to Grayscale
gray = cv2.cvtColor(cropped_plate, cv2.COLOR_BGR2GRAY)

cv2_imshow(gray)


#denoise this
gray = cv2.GaussianBlur(gray, (3,3), 0)


#Threshold
thresh = cv2.threshold(
    gray,
    120,
    255,
    cv2.THRESH_BINARY_INV
)
cv2_imshow(thresh[1])


#Shapen this image

kernel = np.array([
    [-1,-1,-1],
    [-1, 9,-1],
    [-1,-1,-1]
])

sharp = cv2.filter2D(thresh[1], -1, kernel)


#Save the temp file

cv2.imwrite("plate.jpg", sharp)

cv2_imshow(sharp)

#easy ocr reader

reader = easyocr.Reader(["ne"])


allowlist = '०१२३४५६७८९बामेकोसजनागलुधराभेकसेमपप्रखफझबघञया'

result = reader.readtext(
    "plate.jpg",
    detail=0,
    paragraph=False,
    allowlist=allowlist
)

full_text = "".join(result)

valid_chars  = "बामेकोसजनागलुधराभेकसेमपप्रखफझबघञया"
valid_digits = "०१२३४५६७८९"

letters = []
numbers = []

for ch in full_text:
    if ch in valid_chars:
        letters.append(ch)
    elif ch in valid_digits:
        numbers.append(ch)


#Plate ko Format is like this:
# [CHAR][2-DIGIT ZONE][CHAR][SPACE][4-DIGIT NUMBER]       !!!No spacing between characters!!!

first_char = letters[0]  if len(letters) > 0 else ""
middle_num = "".join(numbers[:2]) if len(numbers) >= 2 else "".join(numbers)
last_char  = letters[-1] if len(letters) > 1 else ""
last_4     = "".join(numbers[-4:]) if len(numbers) >= 4 else "".join(numbers[2:])

formatted_plate = first_char + middle_num + last_char + " " + last_4


#Final output

print("Detected Plate:")
formatted_plate